import type { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./i18n/request.ts');

/** The Next.js app that serves the blog, the internal portal and their assets. */
const CONTENT_APP = 'https://groovesheet-content-kelin-studio.vercel.app';
const API_ORIGIN = (process.env.API_ORIGIN || 'https://api.groovesheet.net').replace(/\/+$/, '');

/**
 * The Vercel project still holds these under their CRA names, and the CRA app
 * on main reads them there until this branch merges. Falling back to the old
 * name lets the switch happen with the merge instead of a dashboard rename
 * that would break whichever app is live. Once the project env is renamed,
 * the fallback is dead code and can go.
 */
const PUBLIC_ENV = [
  'ADS_PURCHASE_LABEL', 'AIRWALLEX_ENV', 'API_BASE_URL', 'API_URL', 'CLARITY_ID',
  'ENABLE_ANALYTICS', 'ENABLE_CHAT', 'HUBSPOT_FORM_GUID', 'HUBSPOT_PORTAL_ID',
  'NAME', 'POSTHOG_HOST', 'POSTHOG_KEY', 'SUPABASE_ANON_KEY', 'SUPABASE_URL', 'URL',
];
const publicEnv = Object.fromEntries(
  PUBLIC_ENV.flatMap((name) => {
    const value = process.env[`NEXT_PUBLIC_${name}`] ?? process.env[`REACT_APP_${name}`];
    return value === undefined ? [] : [[`NEXT_PUBLIC_${name}`, value]];
  }),
);

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  env: publicEnv,

  /**
   * These mirror vercel.json. On Vercel, vercel.json rewrites run at the edge
   * before this app is reached, so in production these are a fallback; in
   * `next dev` and `next start` they are what make /api and the content-app
   * paths work at all (the CRA app used src/setupProxy.js for /api only, so
   * /blog and /internal never worked locally before).
   *
   * Order matters: /api/internal must beat /api. Never rewrite /_next here:
   * that is this app's own asset path, and the content app's assets travel
   * under /content-assets instead.
   */
  async rewrites() {
    return [
      { source: '/api/internal/:path*', destination: `${CONTENT_APP}/api/internal/:path*` },
      { source: '/blog', destination: `${CONTENT_APP}/blog` },
      { source: '/blog/:path*', destination: `${CONTENT_APP}/blog/:path*` },
      { source: '/blog-media/:path*', destination: `${CONTENT_APP}/blog-media/:path*` },
      { source: '/internal', destination: `${CONTENT_APP}/internal` },
      { source: '/internal/:path*', destination: `${CONTENT_APP}/internal/:path*` },
      { source: '/content-assets/:path*', destination: `${CONTENT_APP}/content-assets/:path*` },
      { source: '/blog-sitemap.xml', destination: `${CONTENT_APP}/sitemap.xml` },
      { source: '/api/:path*', destination: `${API_ORIGIN}/:path*` },
      // /sitemap.xml is a sitemap index generated by app/sitemap.xml/route.ts.
      // The library child (tracks + creators) still comes from the backend,
      // which owns that data; `scope=library` asks it to leave out the static
      // routes and blog posts that the other children already list.
      { source: '/sitemaps/library.xml', destination: `${API_ORIGIN}/seo/sitemap.xml?scope=library` },
    ];
  },
};

export default withNextIntl(nextConfig);
